### ISSUE TITLE
[Web Scraping] Improve the work with MongoDB

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#11]
## To-Do

- [x] Move connection to a separate package
- [x] Integrate a singleton for `MongoClient`
- [x] Add a database template
- [x] Add a handler of duplicate documents
