### ISSUE TITLE
[Data Analysis] Improve `Wrangler` to work with MongoDB

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#18]
Related to the issue #1 

## To-Do

- [x] Fetch vacancies by a specific period (e.g. for the last month)
- [x] Get the word frequencies
- [x] Save the frequencies to a separate collection

### Extra

- [ ] Add caching of database calls
