### ISSUE TITLE
[Database] Improve the `MongoClient` singleton

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#24]
## To-Do

- [x] Inherit the `MongoClient` instead of assigning it to the variable
- [x] Fix type annotation
- [x] Add more documentation and comments
- [x] Move validation of production parameters to a separate method
