### ISSUE TITLE
[Documentation] Add missing docstrings and compose a README file

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#31]
Related to the issue #1 

## To-Do

- [x] Add missing docstrings
- [x] Add some documentation to the [Jupyter notebook](https://github.com/AndriyKy/tech-trend-stat/blob/develop/techtrendanalysis/analysis.ipynb)
- [x] Compose the README file
