### ISSUE TITLE
[Web Scraping] Scrape Python tech statistics from Djinni

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#4]
Related to the issue #1

https://djinni.co/jobs/keyword-python/

## To-Do

- [x] Add an item (model) based on the "Information to be collected" (use [Pydantic](https://docs.pydantic.dev/latest/));
- [x] Integrate scrapping of the first page only;
- [x] Integrate scrapping of a vacancy;
- [x] Integrate multipage scrapping;
- [x] Add `requirements.txt`.
