### ISSUE TITLE
[Web Scraping] Setting up a pipeline for MongoDB as a primary data store

### ISSUE THREAD

**Issue by AndriyKy** [AndriyKy/tech-trend-stat#9]
Related to the issue #1 

## To-Do

- [x] [Create a project and a cluster on MongoDB](https://www.mongodb.com/docs/atlas/create-connect-deployments/) cloud.
- [x] Install and configure a [MongoDB driver](https://www.mongodb.com/docs/drivers/python-drivers/) ([PyMongo](https://pymongo.readthedocs.io/en/stable/installation.html), [tutorial](https://medium.com/analytics-vidhya/connecting-to-mongodb-atlas-with-python-pymongo-5b25dab3ac53))
- [x] Create a [pipeline](https://docs.scrapy.org/en/latest/topics/item-pipeline.html?highlight=pymongo#write-items-to-mongodb)

### Optional

- [x] Configure a local MongoDB inside a Docker container
- [Use Docker and Python for a MongoDB Application](https://kb.objectrocket.com/mongo-db/use-docker-and-python-for-a-mongodb-application-1046)
- [MongoDB in a Docker container](https://hub.docker.com/_/mongo/?source=post_page-----52f330852b4c--------------------------------)
- [Video tutorial](https://www.google.com/search?q=connect+to+mongodb+using+pymongo+in+a+docker+container&oq=connect+to+mongodb+using+pymongo+in+a+docker+container&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABiABBiiBDIKCAIQABiABBiiBDIKCAMQABiABBiiBDIKCAQQABiABBiiBDIKCAUQABiABBiiBNIBCTIwMDA2ajBqNKgCALACAA&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:7825b659,vid:xb3v2kTJM28,st:0)
